In [1]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import sqlite3
pd.set_option('display.precision', 2)

In [2]:
#connection to databank
conn = sqlite3.connect("../../data/raw/airlines-dataset/travel.sqlite")
cursor = conn.cursor()
cursor.execute("SELECT name FROM sqlite_master WHERE type='table'")
tabels = cursor.fetchall()

print(tabels)

[('aircrafts_data',), ('airports_data',), ('boarding_passes',), ('bookings',), ('flights',), ('seats',), ('ticket_flights',), ('tickets',)]

In [3]:
for tabel in tabels:
    table_name = tabel[0]
    print('table name:', table_name)
    df_tabel = pd.read_sql_query(f"SELECT * FROM {table_name}", conn)
    display(df_tabel)
    print('\n')

table name: aircrafts_data

  aircraft_code                                              model  range
0           773    {"en": "Boeing 777-300", "ru": "Боинг 777-300"}  11100
1           763    {"en": "Boeing 767-300", "ru": "Боинг 767-300"}   7900
2           SU9  {"en": "Sukhoi Superjet-100", "ru": "Сухой Суп...   3000
3           320  {"en": "Airbus A320-200", "ru": "Аэробус A320-...   5700
4           321  {"en": "Airbus A321-200", "ru": "Аэробус A321-...   5600
5           319  {"en": "Airbus A319-100", "ru": "Аэробус A319-...   6700
6           733    {"en": "Boeing 737-300", "ru": "Боинг 737-300"}   4200
7           CN1  {"en": "Cessna 208 Caravan", "ru": "Сессна 208...   1200
8           CR2  {"en": "Bombardier CRJ-200", "ru": "Бомбардье ...   2700

table name: airports_data

,airport_code,airport_name,city,coordinates,timezone
0,YKS,"{""en"": ""Yakutsk Airport"", ""ru"": ""Якутск""}","{""en"": ""Yakutsk"", ""ru"": ""Якутск""}","(129.77099609375,62.0932998657226562)",Asia/Yakutsk
1,MJZ,"{""en"": ""Mirny Airport"", ""ru"": ""Мирный""}","{""en"": ""Mirnyj"", ""ru"": ""Мирный""}","(114.03900146484375,62.534698486328125)",Asia/Yakutsk
2,KHV,"{""en"": ""Khabarovsk-Novy Airport"", ""ru"": ""Хабар...","{""en"": ""Khabarovsk"", ""ru"": ""Хабаровск""}","(135.18800354004,48.5279998779300001)",Asia/Vladivostok
3,PKC,"{""en"": ""Yelizovo Airport"", ""ru"": ""Елизово""}","{""en"": ""Petropavlovsk"", ""ru"": ""Петропавловск-К...","(158.453994750976562,53.1679000854492188)",Asia/Kamchatka
4,UUS,"{""en"": ""Yuzhno-Sakhalinsk Airport"", ""ru"": ""Хом...","{""en"": ""Yuzhno-Sakhalinsk"", ""ru"": ""Южно-Сахали...","(142.718002319335938,46.8886985778808594)",Asia/Sakhalin
...,...,...,...,...,...
99,MMK,"{""en"": ""Murmansk Airport"", ""ru"": ""Мурманск""}","{""en"": ""Murmansk"", ""ru"": ""Мурманск""}","(32.7508010864257812,68.7817001342773438)",Europe/Moscow
100,ABA,"{""en"": ""Abakan Airport"", ""ru"": ""Абакан""}","{""en"": ""Abakan"", ""ru"": ""Абакан""}","(91.3850021362304688,53.7400016784667969)",Asia/Krasnoyarsk
101,BAX,"{""en"": ""Barnaul Airport"", ""ru"": ""Барнаул""}","{""en"": ""Barnaul"", ""ru"": ""Барнаул""}","(83.5384979248046875,53.363800048828125)",Asia/Krasnoyarsk
102,AAQ,"{""en"": ""Anapa Vityazevo Airport"", ""ru"": ""Витяз...","{""en"": ""Anapa"", ""ru"": ""Анапа""}","(37.3473014831539984,45.002101898192997)",Europe/Moscow
103,CNN,"{""en"": ""Chulman Airport"", ""ru"": ""Чульман""}","{""en"": ""Neryungri"", ""ru"": ""Нерюнгри""}","(124.914001464839998,56.9138984680179973)",Asia/Yakutsk

table name: boarding_passes

            ticket_no  flight_id  boarding_no seat_no
0       0005435212351      30625            1      2D
1       0005435212386      30625            2      3G
2       0005435212381      30625            3      4H
3       0005432211370      30625            4      5D
4       0005435212357      30625            5     11A
...               ...        ...          ...     ...
579681  0005434302871      19945           85     20F
579682  0005432892791      19945           86     21C
579683  0005434302869      19945           87     20E
579684  0005432802476      19945           88     21F
579685  0005432802482      19945           89     21E

[579686 rows x 4 columns]

table name: bookings

       book_ref               book_date  total_amount
0        00000F  2017-07-05 03:12:00+03        265700
1        000012  2017-07-14 09:02:00+03         37900
2        000068  2017-08-15 14:27:00+03         18100
3        000181  2017-08-10 13:28:00+03        131800
4        0002D8  2017-08-07 21:40:00+03         23600
...         ...                     ...           ...
262783   FFFEF3  2017-07-17 07:23:00+03         56000
262784   FFFF2C  2017-08-08 05:55:00+03         10800
262785   FFFF43  2017-07-20 20:42:00+03         78500
262786   FFFFA8  2017-08-08 04:45:00+03         28800
262787   FFFFF7  2017-07-01 22:12:00+03         73600

[262788 rows x 3 columns]

table name: flights

,flight_id,flight_no,scheduled_departure,scheduled_arrival,departure_airport,arrival_airport,status,aircraft_code,actual_departure,actual_arrival
0,1185,PG0134,2017-09-10 09:50:00+03,2017-09-10 14:55:00+03,DME,BTK,Scheduled,319,\N,\N
1,3979,PG0052,2017-08-25 14:50:00+03,2017-08-25 17:35:00+03,VKO,HMA,Scheduled,CR2,\N,\N
2,4739,PG0561,2017-09-05 12:30:00+03,2017-09-05 14:15:00+03,VKO,AER,Scheduled,763,\N,\N
3,5502,PG0529,2017-09-12 09:50:00+03,2017-09-12 11:20:00+03,SVO,UFA,Scheduled,763,\N,\N
4,6938,PG0461,2017-09-04 12:25:00+03,2017-09-04 13:20:00+03,SVO,ULV,Scheduled,SU9,\N,\N
...,...,...,...,...,...,...,...,...,...,...
33116,33117,PG0063,2017-08-02 19:25:00+03,2017-08-02 20:10:00+03,SKX,SVO,Arrived,CR2,2017-08-02 19:25:00+03,2017-08-02 20:10:00+03
33117,33118,PG0063,2017-07-28 19:25:00+03,2017-07-28 20:10:00+03,SKX,SVO,Arrived,CR2,2017-07-28 19:30:00+03,2017-07-28 20:15:00+03
33118,33119,PG0063,2017-09-08 19:25:00+03,2017-09-08 20:10:00+03,SKX,SVO,Scheduled,CR2,\N,\N
33119,33120,PG0063,2017-08-01 19:25:00+03,2017-08-01 20:10:00+03,SKX,SVO,Arrived,CR2,2017-08-01 19:26:00+03,2017-08-01 20:12:00+03
33120,33121,PG0063,2017-08-26 19:25:00+03,2017-08-26 20:10:00+03,SKX,SVO,Scheduled,CR2,\N,\N

table name: seats

     aircraft_code seat_no fare_conditions
0              319      2A        Business
1              319      2C        Business
2              319      2D        Business
3              319      2F        Business
4              319      3A        Business
...            ...     ...             ...
1334           773     48H         Economy
1335           773     48K         Economy
1336           773     49A         Economy
1337           773     49C         Economy
1338           773     49D         Economy

[1339 rows x 3 columns]

table name: ticket_flights

             ticket_no  flight_id fare_conditions  amount
0        0005432159776      30625        Business   42100
1        0005435212351      30625        Business   42100
2        0005435212386      30625        Business   42100
3        0005435212381      30625        Business   42100
4        0005432211370      30625        Business   42100
...                ...        ...             ...     ...
1045721  0005435097522      32094         Economy    5200
1045722  0005435097521      32094         Economy    5200
1045723  0005435104384      32094         Economy    5200
1045724  0005435104352      32094         Economy    5200
1045725  0005435104389      32094         Economy    5200

[1045726 rows x 4 columns]

table name: tickets

            ticket_no book_ref passenger_id
0       0005432000987   06B046  8149 604011
1       0005432000988   06B046  8499 420203
2       0005432000989   E170C3  1011 752484
3       0005432000990   E170C3  4849 400049
4       0005432000991   F313DD  6615 976589
...               ...      ...          ...
366728  0005435999869   D730BA  0474 690760
366729  0005435999870   D730BA  6535 751108
366730  0005435999871   A1AD46  1596 156448
366731  0005435999872   7B6A53  9374 822707
366732  0005435999873   7B6A53  7380 075822

[366733 rows x 3 columns]

In [4]:
#Die explorative Datenanalyse (EDA)
for tabel in tabels:
    table_name = tabel[0]
    print('table name:', table_name)
    df_tabel = pd.read_sql_query(f"SELECT * FROM {table_name}", conn)
    display(
        "Shape",
        df_tabel.shape,
    "Description",
    df_tabel.describe().round(2).T,
    "Duplicates",
    df_tabel.duplicated().sum(),
    )


    overview = pd.DataFrame(
        {
            "Data Types": df_tabel.dtypes,
            "Missing Values": df_tabel.isnull().sum(),
            "Unique Values": df_tabel.nunique(),
            "Sample Values": [df_tabel[col].sample(3).tolist() for col in df_tabel.columns]
        })
    display(overview)
    print('missing values')
    display(df_tabel.isna().sum())
    print('\n'*2)

table name: aircrafts_data

'Shape'

(9, 3)

'Description'

       count     mean      std     min     25%     50%     75%      max
range    9.0  5344.44  3013.76  1200.0  3000.0  5600.0  6700.0  11100.0

'Duplicates'

np.int64(0)

,Data Types,Missing Values,Unique Values,Sample Values
aircraft_code,object,0,9,"[733, CR2, 320]"
model,object,0,9,"[{""en"": ""Boeing 767-300"", ""ru"": ""Боинг 767-300..."
range,int64,0,9,"[11100, 4200, 1200]"

missing values

aircraft_code    0
model            0
range            0
dtype: int64

table name: airports_data

'Shape'

(104, 5)

'Description'

             count unique                                        top freq
airport_code   104    104                                        YKS    1
airport_name   104    104  {"en": "Yakutsk Airport", "ru": "Якутск"}    1
city           104    101           {"en": "Moscow", "ru": "Москва"}    3
coordinates    104    104      (129.77099609375,62.0932998657226562)    1
timezone       104     17                              Europe/Moscow   44

'Duplicates'

np.int64(0)

,Data Types,Missing Values,Unique Values,Sample Values
airport_code,object,0,104,"[REN, KXK, NNM]"
airport_name,object,0,104,"[{""en"": ""Nalchik Airport"", ""ru"": ""Нальчик""}, {..."
city,object,0,101,"[{""en"": ""Ust-Kut"", ""ru"": ""Усть-Кут""}, {""en"": ""..."
coordinates,object,0,104,"[(72.6988983154296875,65.4809036254882812), (4..."
timezone,object,0,17,"[Asia/Krasnoyarsk, Europe/Moscow, Asia/Novokuz..."

missing values

airport_code    0
airport_name    0
city            0
coordinates     0
timezone        0
dtype: int64

table name: boarding_passes

'Shape'

(579686, 4)

'Description'

,count,mean,std,min,25%,50%,75%,max
flight_id,579686.0,13720.82,9713.92,1.0,5351.0,11217.0,22481.0,33120.0
boarding_no,579686.0,54.97,58.82,1.0,15.0,36.0,72.0,374.0

'Duplicates'

np.int64(0)

,Data Types,Missing Values,Unique Values,Sample Values
ticket_no,object,0,238834,"[0005433719112, 0005433985997, 0005435373759]"
flight_id,int64,0,11518,"[6330, 24844, 20328]"
boarding_no,int64,0,374,"[17, 32, 39]"
seat_no,object,0,461,"[13D, 14E, 3C]"

missing values

ticket_no      0
flight_id      0
boarding_no    0
seat_no        0
dtype: int64

table name: bookings

'Shape'

(262788, 3)

'Description'

,count,mean,std,min,25%,50%,75%,max
total_amount,262788.0,79025.61,77621.92,3400.0,29000.0,55900.0,99200.0,1.20e+06

'Duplicates'

np.int64(0)

,Data Types,Missing Values,Unique Values,Sample Values
book_ref,object,0,262788,"[B59F3E, 9FFA35, E1870B]"
book_date,object,0,68631,"[2017-07-27 11:53:00+03, 2017-08-04 00:48:00+0..."
total_amount,int64,0,3926,"[121400, 67600, 30200]"

missing values

book_ref        0
book_date       0
total_amount    0
dtype: int64

table name: flights

'Shape'

(33121, 10)

'Description'

             count     mean      std  min     25%      50%      75%      max
flight_id  33121.0  16561.0  9561.35  1.0  8281.0  16561.0  24841.0  33121.0

'Duplicates'

np.int64(0)

,Data Types,Missing Values,Unique Values,Sample Values
flight_id,int64,0,33121,"[21749, 10565, 30077]"
flight_no,object,0,710,"[PG0234, PG0215, PG0628]"
scheduled_departure,object,0,10365,"[2017-09-02 16:05:00+03, 2017-08-19 13:50:00+0..."
scheduled_arrival,object,0,9648,"[2017-08-30 18:35:00+03, 2017-09-09 12:50:00+0..."
departure_airport,object,0,104,"[AER, LED, ASF]"
arrival_airport,object,0,104,"[GRV, REN, ARH]"
status,object,0,6,"[Scheduled, Scheduled, Arrived]"
aircraft_code,object,0,8,"[CN1, CN1, SU9]"
actual_departure,object,0,12108,"[2017-08-11 13:27:00+03, \N, \N]"
actual_arrival,object,0,11851,"[2017-07-24 12:52:00+03, 2017-07-16 14:36:00+0..."

missing values

flight_id              0
flight_no              0
scheduled_departure    0
scheduled_arrival      0
departure_airport      0
arrival_airport        0
status                 0
aircraft_code          0
actual_departure       0
actual_arrival         0
dtype: int64

table name: seats

'Shape'

(1339, 3)

'Description'

                count unique      top  freq
aircraft_code    1339      9      773   402
seat_no          1339    461       1A     9
fare_conditions  1339      3  Economy  1139

'Duplicates'

np.int64(0)

,Data Types,Missing Values,Unique Values,Sample Values
aircraft_code,object,0,9,"[763, 773, 773]"
seat_no,object,0,461,"[24B, 32E, 20D]"
fare_conditions,object,0,3,"[Economy, Economy, Economy]"

missing values

aircraft_code      0
seat_no            0
fare_conditions    0
dtype: int64

table name: ticket_flights

'Shape'

(1045726, 4)

'Description'

,count,mean,std,min,25%,50%,75%,max
flight_id,1.05e+06,14110.06,9732.94,1.0,5501.0,11926.0,23039.0,33121.0
amount,1.05e+06,19858.91,22612.39,3000.0,7200.0,13400.0,23100.0,203300.0

'Duplicates'

np.int64(0)

,Data Types,Missing Values,Unique Values,Sample Values
ticket_no,object,0,366733,"[0005433368709, 0005433507166, 0005434143717]"
flight_id,int64,0,22226,"[15318, 3512, 24627]"
fare_conditions,object,0,3,"[Economy, Economy, Economy]"
amount,int64,0,338,"[41200, 6700, 3200]"

missing values

ticket_no          0
flight_id          0
fare_conditions    0
amount             0
dtype: int64

table name: tickets

'Shape'

(366733, 3)

'Description'

               count  unique            top freq
ticket_no     366733  366733  0005432000987    1
book_ref      366733  262788         979E64    5
passenger_id  366733  366733    8149 604011    1

'Duplicates'

np.int64(0)

,Data Types,Missing Values,Unique Values,Sample Values
ticket_no,object,0,366733,"[0005432261237, 0005435982971, 0005434266024]"
book_ref,object,0,262788,"[1B77A9, 8B3199, 66913D]"
passenger_id,object,0,366733,"[2944 584367, 5338 262866, 0194 413221]"

missing values

ticket_no       0
book_ref        0
passenger_id    0
dtype: int64

In [5]:
#
numeric_to_categoric_columns = ['flight_id', 'flight_no']
date_columns = ['scheduled_departure', 'scheduled_arrival', 'actual_departure', 'actual_arrival', 'book_date']
for tabel in tabels:
    table_name = tabel[0]
    print('table name:', table_name)
    df_tabel = pd.read_sql_query(f"SELECT * FROM {table_name}", conn)
    for column in numeric_to_categoric_columns:
        if column in df_tabel.columns:
            df_tabel[column] = df_tabel[column].astype('category')
    if 'coordinates' in  df_tabel.columns:
        df_tabel[['longitude', 'latitude']] = (df_tabel['coordinates'].str.strip('()').str.split(',', expand=True).astype(float))
    object_columns = df_tabel.select_dtypes(include=['object']).columns.tolist()
    for column in object_columns:
        df_tabel[column]=df_tabel[column].astype('category')
    display(df_tabel.dtypes)
    display(df_tabel)
    print('\n'*2)

table name: aircrafts_data

aircraft_code    category
model            category
range               int64
dtype: object

  aircraft_code                                              model  range
0           773    {"en": "Boeing 777-300", "ru": "Боинг 777-300"}  11100
1           763    {"en": "Boeing 767-300", "ru": "Боинг 767-300"}   7900
2           SU9  {"en": "Sukhoi Superjet-100", "ru": "Сухой Суп...   3000
3           320  {"en": "Airbus A320-200", "ru": "Аэробус A320-...   5700
4           321  {"en": "Airbus A321-200", "ru": "Аэробус A321-...   5600
5           319  {"en": "Airbus A319-100", "ru": "Аэробус A319-...   6700
6           733    {"en": "Boeing 737-300", "ru": "Боинг 737-300"}   4200
7           CN1  {"en": "Cessna 208 Caravan", "ru": "Сессна 208...   1200
8           CR2  {"en": "Bombardier CRJ-200", "ru": "Бомбардье ...   2700

table name: airports_data

airport_code    category
airport_name    category
city            category
coordinates     category
timezone        category
longitude        float64
latitude         float64
dtype: object

,airport_code,airport_name,city,coordinates,timezone,longitude,latitude
0,YKS,"{""en"": ""Yakutsk Airport"", ""ru"": ""Якутск""}","{""en"": ""Yakutsk"", ""ru"": ""Якутск""}","(129.77099609375,62.0932998657226562)",Asia/Yakutsk,129.77,62.09
1,MJZ,"{""en"": ""Mirny Airport"", ""ru"": ""Мирный""}","{""en"": ""Mirnyj"", ""ru"": ""Мирный""}","(114.03900146484375,62.534698486328125)",Asia/Yakutsk,114.04,62.53
2,KHV,"{""en"": ""Khabarovsk-Novy Airport"", ""ru"": ""Хабар...","{""en"": ""Khabarovsk"", ""ru"": ""Хабаровск""}","(135.18800354004,48.5279998779300001)",Asia/Vladivostok,135.19,48.53
3,PKC,"{""en"": ""Yelizovo Airport"", ""ru"": ""Елизово""}","{""en"": ""Petropavlovsk"", ""ru"": ""Петропавловск-К...","(158.453994750976562,53.1679000854492188)",Asia/Kamchatka,158.45,53.17
4,UUS,"{""en"": ""Yuzhno-Sakhalinsk Airport"", ""ru"": ""Хом...","{""en"": ""Yuzhno-Sakhalinsk"", ""ru"": ""Южно-Сахали...","(142.718002319335938,46.8886985778808594)",Asia/Sakhalin,142.72,46.89
...,...,...,...,...,...,...,...
99,MMK,"{""en"": ""Murmansk Airport"", ""ru"": ""Мурманск""}","{""en"": ""Murmansk"", ""ru"": ""Мурманск""}","(32.7508010864257812,68.7817001342773438)",Europe/Moscow,32.75,68.78
100,ABA,"{""en"": ""Abakan Airport"", ""ru"": ""Абакан""}","{""en"": ""Abakan"", ""ru"": ""Абакан""}","(91.3850021362304688,53.7400016784667969)",Asia/Krasnoyarsk,91.39,53.74
101,BAX,"{""en"": ""Barnaul Airport"", ""ru"": ""Барнаул""}","{""en"": ""Barnaul"", ""ru"": ""Барнаул""}","(83.5384979248046875,53.363800048828125)",Asia/Krasnoyarsk,83.54,53.36
102,AAQ,"{""en"": ""Anapa Vityazevo Airport"", ""ru"": ""Витяз...","{""en"": ""Anapa"", ""ru"": ""Анапа""}","(37.3473014831539984,45.002101898192997)",Europe/Moscow,37.35,45.00
103,CNN,"{""en"": ""Chulman Airport"", ""ru"": ""Чульман""}","{""en"": ""Neryungri"", ""ru"": ""Нерюнгри""}","(124.914001464839998,56.9138984680179973)",Asia/Yakutsk,124.91,56.91

table name: boarding_passes

ticket_no      category
flight_id      category
boarding_no       int64
seat_no        category
dtype: object

            ticket_no flight_id  boarding_no seat_no
0       0005435212351     30625            1      2D
1       0005435212386     30625            2      3G
2       0005435212381     30625            3      4H
3       0005432211370     30625            4      5D
4       0005435212357     30625            5     11A
...               ...       ...          ...     ...
579681  0005434302871     19945           85     20F
579682  0005432892791     19945           86     21C
579683  0005434302869     19945           87     20E
579684  0005432802476     19945           88     21F
579685  0005432802482     19945           89     21E

[579686 rows x 4 columns]

table name: bookings

book_ref        category
book_date       category
total_amount       int64
dtype: object

       book_ref               book_date  total_amount
0        00000F  2017-07-05 03:12:00+03        265700
1        000012  2017-07-14 09:02:00+03         37900
2        000068  2017-08-15 14:27:00+03         18100
3        000181  2017-08-10 13:28:00+03        131800
4        0002D8  2017-08-07 21:40:00+03         23600
...         ...                     ...           ...
262783   FFFEF3  2017-07-17 07:23:00+03         56000
262784   FFFF2C  2017-08-08 05:55:00+03         10800
262785   FFFF43  2017-07-20 20:42:00+03         78500
262786   FFFFA8  2017-08-08 04:45:00+03         28800
262787   FFFFF7  2017-07-01 22:12:00+03         73600

[262788 rows x 3 columns]

table name: flights

flight_id              category
flight_no              category
scheduled_departure    category
scheduled_arrival      category
departure_airport      category
arrival_airport        category
status                 category
aircraft_code          category
actual_departure       category
actual_arrival         category
dtype: object

,flight_id,flight_no,scheduled_departure,scheduled_arrival,departure_airport,arrival_airport,status,aircraft_code,actual_departure,actual_arrival
0,1185,PG0134,2017-09-10 09:50:00+03,2017-09-10 14:55:00+03,DME,BTK,Scheduled,319,\N,\N
1,3979,PG0052,2017-08-25 14:50:00+03,2017-08-25 17:35:00+03,VKO,HMA,Scheduled,CR2,\N,\N
2,4739,PG0561,2017-09-05 12:30:00+03,2017-09-05 14:15:00+03,VKO,AER,Scheduled,763,\N,\N
3,5502,PG0529,2017-09-12 09:50:00+03,2017-09-12 11:20:00+03,SVO,UFA,Scheduled,763,\N,\N
4,6938,PG0461,2017-09-04 12:25:00+03,2017-09-04 13:20:00+03,SVO,ULV,Scheduled,SU9,\N,\N
...,...,...,...,...,...,...,...,...,...,...
33116,33117,PG0063,2017-08-02 19:25:00+03,2017-08-02 20:10:00+03,SKX,SVO,Arrived,CR2,2017-08-02 19:25:00+03,2017-08-02 20:10:00+03
33117,33118,PG0063,2017-07-28 19:25:00+03,2017-07-28 20:10:00+03,SKX,SVO,Arrived,CR2,2017-07-28 19:30:00+03,2017-07-28 20:15:00+03
33118,33119,PG0063,2017-09-08 19:25:00+03,2017-09-08 20:10:00+03,SKX,SVO,Scheduled,CR2,\N,\N
33119,33120,PG0063,2017-08-01 19:25:00+03,2017-08-01 20:10:00+03,SKX,SVO,Arrived,CR2,2017-08-01 19:26:00+03,2017-08-01 20:12:00+03
33120,33121,PG0063,2017-08-26 19:25:00+03,2017-08-26 20:10:00+03,SKX,SVO,Scheduled,CR2,\N,\N

table name: seats

aircraft_code      category
seat_no            category
fare_conditions    category
dtype: object

     aircraft_code seat_no fare_conditions
0              319      2A        Business
1              319      2C        Business
2              319      2D        Business
3              319      2F        Business
4              319      3A        Business
...            ...     ...             ...
1334           773     48H         Economy
1335           773     48K         Economy
1336           773     49A         Economy
1337           773     49C         Economy
1338           773     49D         Economy

[1339 rows x 3 columns]

table name: ticket_flights

ticket_no          category
flight_id          category
fare_conditions    category
amount                int64
dtype: object

             ticket_no flight_id fare_conditions  amount
0        0005432159776     30625        Business   42100
1        0005435212351     30625        Business   42100
2        0005435212386     30625        Business   42100
3        0005435212381     30625        Business   42100
4        0005432211370     30625        Business   42100
...                ...       ...             ...     ...
1045721  0005435097522     32094         Economy    5200
1045722  0005435097521     32094         Economy    5200
1045723  0005435104384     32094         Economy    5200
1045724  0005435104352     32094         Economy    5200
1045725  0005435104389     32094         Economy    5200

[1045726 rows x 4 columns]

table name: tickets

ticket_no       category
book_ref        category
passenger_id    category
dtype: object

            ticket_no book_ref passenger_id
0       0005432000987   06B046  8149 604011
1       0005432000988   06B046  8499 420203
2       0005432000989   E170C3  1011 752484
3       0005432000990   E170C3  4849 400049
4       0005432000991   F313DD  6615 976589
...               ...      ...          ...
366728  0005435999869   D730BA  0474 690760
366729  0005435999870   D730BA  6535 751108
366730  0005435999871   A1AD46  1596 156448
366731  0005435999872   7B6A53  9374 822707
366732  0005435999873   7B6A53  7380 075822

[366733 rows x 3 columns]

In [8]:
for tabel in tabels:
    table_name = tabel[0]
    df_tabel = pd.read_sql_query(f"SELECT * FROM {table_name}", conn)

In [9]:
#closing the connection to databank
#conn.close()