In [1]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import sqlite3
pd.set_option('display.precision', 2)

In [2]:
#connection to databank
conn = sqlite3.connect("../../data/raw/airlines-dataset/travel.sqlite")
cursor = conn.cursor()
cursor.execute("SELECT name FROM sqlite_master WHERE type='table'")
tabels = cursor.fetchall()

print(tabels)

[('aircrafts_data',), ('airports_data',), ('boarding_passes',), ('bookings',), ('flights',), ('seats',), ('ticket_flights',), ('tickets',), ('load_factor_departure_airport',), ('load_factor_arrival_airport',)]

In [3]:
for tabel in tabels:
    table_name = tabel[0]
    print('table name:', table_name)
    df_tabel = pd.read_sql_query(f"SELECT * FROM {table_name}", conn)
    display(df_tabel)
    print('\n')

table name: aircrafts_data

  aircraft_code                                              model  range
0           773    {"en": "Boeing 777-300", "ru": "Боинг 777-300"}  11100
1           763    {"en": "Boeing 767-300", "ru": "Боинг 767-300"}   7900
2           SU9  {"en": "Sukhoi Superjet-100", "ru": "Сухой Суп...   3000
3           320  {"en": "Airbus A320-200", "ru": "Аэробус A320-...   5700
4           321  {"en": "Airbus A321-200", "ru": "Аэробус A321-...   5600
5           319  {"en": "Airbus A319-100", "ru": "Аэробус A319-...   6700
6           733    {"en": "Boeing 737-300", "ru": "Боинг 737-300"}   4200
7           CN1  {"en": "Cessna 208 Caravan", "ru": "Сессна 208...   1200
8           CR2  {"en": "Bombardier CRJ-200", "ru": "Бомбардье ...   2700

table name: airports_data

,airport_code,airport_name,city,coordinates,timezone
0,YKS,"{""en"": ""Yakutsk Airport"", ""ru"": ""Якутск""}","{""en"": ""Yakutsk"", ""ru"": ""Якутск""}","(129.77099609375,62.0932998657226562)",Asia/Yakutsk
1,MJZ,"{""en"": ""Mirny Airport"", ""ru"": ""Мирный""}","{""en"": ""Mirnyj"", ""ru"": ""Мирный""}","(114.03900146484375,62.534698486328125)",Asia/Yakutsk
2,KHV,"{""en"": ""Khabarovsk-Novy Airport"", ""ru"": ""Хабар...","{""en"": ""Khabarovsk"", ""ru"": ""Хабаровск""}","(135.18800354004,48.5279998779300001)",Asia/Vladivostok
3,PKC,"{""en"": ""Yelizovo Airport"", ""ru"": ""Елизово""}","{""en"": ""Petropavlovsk"", ""ru"": ""Петропавловск-К...","(158.453994750976562,53.1679000854492188)",Asia/Kamchatka
4,UUS,"{""en"": ""Yuzhno-Sakhalinsk Airport"", ""ru"": ""Хом...","{""en"": ""Yuzhno-Sakhalinsk"", ""ru"": ""Южно-Сахали...","(142.718002319335938,46.8886985778808594)",Asia/Sakhalin
...,...,...,...,...,...
99,MMK,"{""en"": ""Murmansk Airport"", ""ru"": ""Мурманск""}","{""en"": ""Murmansk"", ""ru"": ""Мурманск""}","(32.7508010864257812,68.7817001342773438)",Europe/Moscow
100,ABA,"{""en"": ""Abakan Airport"", ""ru"": ""Абакан""}","{""en"": ""Abakan"", ""ru"": ""Абакан""}","(91.3850021362304688,53.7400016784667969)",Asia/Krasnoyarsk
101,BAX,"{""en"": ""Barnaul Airport"", ""ru"": ""Барнаул""}","{""en"": ""Barnaul"", ""ru"": ""Барнаул""}","(83.5384979248046875,53.363800048828125)",Asia/Krasnoyarsk
102,AAQ,"{""en"": ""Anapa Vityazevo Airport"", ""ru"": ""Витяз...","{""en"": ""Anapa"", ""ru"": ""Анапа""}","(37.3473014831539984,45.002101898192997)",Europe/Moscow
103,CNN,"{""en"": ""Chulman Airport"", ""ru"": ""Чульман""}","{""en"": ""Neryungri"", ""ru"": ""Нерюнгри""}","(124.914001464839998,56.9138984680179973)",Asia/Yakutsk

table name: boarding_passes

            ticket_no  flight_id  boarding_no seat_no
0       0005435212351      30625            1      2D
1       0005435212386      30625            2      3G
2       0005435212381      30625            3      4H
3       0005432211370      30625            4      5D
4       0005435212357      30625            5     11A
...               ...        ...          ...     ...
579681  0005434302871      19945           85     20F
579682  0005432892791      19945           86     21C
579683  0005434302869      19945           87     20E
579684  0005432802476      19945           88     21F
579685  0005432802482      19945           89     21E

[579686 rows x 4 columns]

table name: bookings

       book_ref               book_date  total_amount
0        00000F  2017-07-05 03:12:00+03        265700
1        000012  2017-07-14 09:02:00+03         37900
2        000068  2017-08-15 14:27:00+03         18100
3        000181  2017-08-10 13:28:00+03        131800
4        0002D8  2017-08-07 21:40:00+03         23600
...         ...                     ...           ...
262783   FFFEF3  2017-07-17 07:23:00+03         56000
262784   FFFF2C  2017-08-08 05:55:00+03         10800
262785   FFFF43  2017-07-20 20:42:00+03         78500
262786   FFFFA8  2017-08-08 04:45:00+03         28800
262787   FFFFF7  2017-07-01 22:12:00+03         73600

[262788 rows x 3 columns]

table name: flights

,flight_id,flight_no,scheduled_departure,scheduled_arrival,departure_airport,arrival_airport,status,aircraft_code,actual_departure,actual_arrival
0,1185,PG0134,2017-09-10 09:50:00+03,2017-09-10 14:55:00+03,DME,BTK,Scheduled,319,\N,\N
1,3979,PG0052,2017-08-25 14:50:00+03,2017-08-25 17:35:00+03,VKO,HMA,Scheduled,CR2,\N,\N
2,4739,PG0561,2017-09-05 12:30:00+03,2017-09-05 14:15:00+03,VKO,AER,Scheduled,763,\N,\N
3,5502,PG0529,2017-09-12 09:50:00+03,2017-09-12 11:20:00+03,SVO,UFA,Scheduled,763,\N,\N
4,6938,PG0461,2017-09-04 12:25:00+03,2017-09-04 13:20:00+03,SVO,ULV,Scheduled,SU9,\N,\N
...,...,...,...,...,...,...,...,...,...,...
33116,33117,PG0063,2017-08-02 19:25:00+03,2017-08-02 20:10:00+03,SKX,SVO,Arrived,CR2,2017-08-02 19:25:00+03,2017-08-02 20:10:00+03
33117,33118,PG0063,2017-07-28 19:25:00+03,2017-07-28 20:10:00+03,SKX,SVO,Arrived,CR2,2017-07-28 19:30:00+03,2017-07-28 20:15:00+03
33118,33119,PG0063,2017-09-08 19:25:00+03,2017-09-08 20:10:00+03,SKX,SVO,Scheduled,CR2,\N,\N
33119,33120,PG0063,2017-08-01 19:25:00+03,2017-08-01 20:10:00+03,SKX,SVO,Arrived,CR2,2017-08-01 19:26:00+03,2017-08-01 20:12:00+03
33120,33121,PG0063,2017-08-26 19:25:00+03,2017-08-26 20:10:00+03,SKX,SVO,Scheduled,CR2,\N,\N

table name: seats

     aircraft_code seat_no fare_conditions
0              319      2A        Business
1              319      2C        Business
2              319      2D        Business
3              319      2F        Business
4              319      3A        Business
...            ...     ...             ...
1334           773     48H         Economy
1335           773     48K         Economy
1336           773     49A         Economy
1337           773     49C         Economy
1338           773     49D         Economy

[1339 rows x 3 columns]

table name: ticket_flights

             ticket_no  flight_id fare_conditions  amount
0        0005432159776      30625        Business   42100
1        0005435212351      30625        Business   42100
2        0005435212386      30625        Business   42100
3        0005435212381      30625        Business   42100
4        0005432211370      30625        Business   42100
...                ...        ...             ...     ...
1045721  0005435097522      32094         Economy    5200
1045722  0005435097521      32094         Economy    5200
1045723  0005435104384      32094         Economy    5200
1045724  0005435104352      32094         Economy    5200
1045725  0005435104389      32094         Economy    5200

[1045726 rows x 4 columns]

table name: tickets

            ticket_no book_ref passenger_id
0       0005432000987   06B046  8149 604011
1       0005432000988   06B046  8499 420203
2       0005432000989   E170C3  1011 752484
3       0005432000990   E170C3  4849 400049
4       0005432000991   F313DD  6615 976589
...               ...      ...          ...
366728  0005435999869   D730BA  0474 690760
366729  0005435999870   D730BA  6535 751108
366730  0005435999871   A1AD46  1596 156448
366731  0005435999872   7B6A53  9374 822707
366732  0005435999873   7B6A53  7380 075822

[366733 rows x 3 columns]

table name: load_factor_departure_airport

,departure_airport,total_flights,total_occupied_seats,total_available_seats,load_factor
0,URJ,122,4352,11834,0.37
1,KVX,366,9146,25132,0.36
2,MCX,200,6220,17747,0.35
3,NNM,157,2608,7850,0.33
4,AAQ,131,4942,15017,0.33
...,...,...,...,...,...
99,KYZ,43,0,820,0.00
100,JOK,261,0,3778,0.00
101,IWA,34,0,1700,0.00
102,IAR,79,0,1632,0.00
103,EYK,53,0,978,0.00

table name: load_factor_arrival_airport

,arrival_airport,total_flights,total_occupied_seats,total_available_seats,load_factor
0,AAQ,131,5990,15017,0.40
1,KVX,366,9545,25132,0.38
2,URJ,122,4432,11834,0.37
3,MCX,201,6632,17797,0.37
4,KUF,183,7632,22204,0.34
...,...,...,...,...,...
99,KYZ,44,0,870,0.00
100,JOK,262,0,3828,0.00
101,IWA,36,0,1800,0.00
102,IAR,79,0,1632,0.00
103,EYK,53,0,978,0.00

In [4]:
#closing the connection to databank
conn.close()

In [5]:
#Die explorative Datenanalyse (EDA)
for tabel in tabels:
    print('name of table:', tabel)
    display(
        "Shape",
        df_tabel.shape,
    "Description",
    df_tabel.describe().round(2).T,
    "Duplicates",
    df_tabel.duplicated().sum(),
    )


    overview = pd.DataFrame(
        {
            "Data Types": df_tabel.dtypes,
            "Missing Values": df_tabel.isnull().sum(),
            "Unique Values": df_tabel.nunique(),
            "Sample Values": [df_tabel[col].sample(3).tolist() for col in df_tabel.columns]
        })
    display(overview)
    print('missing values')
    display(df_tabel.isna())
    print('\n'*2)

name of table: ('aircrafts_data',)

'Shape'

(104, 5)

'Description'

,count,mean,std,min,25%,50%,75%,max
total_flights,104.0,318.47,483.64,17.0,120.00,187.00,359.00,3217.0
total_occupied_seats,104.0,5573.90,11807.55,0.0,421.00,2130.50,5997.75,77909.0
total_available_seats,104.0,24481.06,51602.93,528.0,4440.50,9057.50,22280.25,327936.0
load_factor,104.0,0.18,0.11,0.0,0.11,0.18,0.27,0.4

'Duplicates'

np.int64(0)

,Data Types,Missing Values,Unique Values,Sample Values
arrival_airport,object,0,104,"[BTK, MRV, UKX]"
total_flights,int64,0,72,"[296, 53, 366]"
total_occupied_seats,int64,0,95,"[7285, 2681, 2803]"
total_available_seats,int64,0,99,"[15647, 52115, 203652]"
load_factor,float64,0,95,"[0.2715272471194618, 0.0, 0.1723955579058699]"

missing values

,arrival_airport,total_flights,total_occupied_seats,total_available_seats,load_factor
0,False,False,False,False,False
1,False,False,False,False,False
2,False,False,False,False,False
3,False,False,False,False,False
4,False,False,False,False,False
...,...,...,...,...,...
99,False,False,False,False,False
100,False,False,False,False,False
101,False,False,False,False,False
102,False,False,False,False,False
103,False,False,False,False,False

name of table: ('airports_data',)

'Shape'

(104, 5)

'Description'

,count,mean,std,min,25%,50%,75%,max
total_flights,104.0,318.47,483.64,17.0,120.00,187.00,359.00,3217.0
total_occupied_seats,104.0,5573.90,11807.55,0.0,421.00,2130.50,5997.75,77909.0
total_available_seats,104.0,24481.06,51602.93,528.0,4440.50,9057.50,22280.25,327936.0
load_factor,104.0,0.18,0.11,0.0,0.11,0.18,0.27,0.4

'Duplicates'

np.int64(0)

,Data Types,Missing Values,Unique Values,Sample Values
arrival_airport,object,0,104,"[SVX, NOZ, MMK]"
total_flights,int64,0,72,"[140, 96, 688]"
total_occupied_seats,int64,0,95,"[622, 1155, 5071]"
total_available_seats,int64,0,99,"[4220, 92518, 19947]"
load_factor,float64,0,95,"[0.2969908558334594, 0.10282282282282282, 0.03..."

missing values

,arrival_airport,total_flights,total_occupied_seats,total_available_seats,load_factor
0,False,False,False,False,False
1,False,False,False,False,False
2,False,False,False,False,False
3,False,False,False,False,False
4,False,False,False,False,False
...,...,...,...,...,...
99,False,False,False,False,False
100,False,False,False,False,False
101,False,False,False,False,False
102,False,False,False,False,False
103,False,False,False,False,False

name of table: ('boarding_passes',)

'Shape'

(104, 5)

'Description'

,count,mean,std,min,25%,50%,75%,max
total_flights,104.0,318.47,483.64,17.0,120.00,187.00,359.00,3217.0
total_occupied_seats,104.0,5573.90,11807.55,0.0,421.00,2130.50,5997.75,77909.0
total_available_seats,104.0,24481.06,51602.93,528.0,4440.50,9057.50,22280.25,327936.0
load_factor,104.0,0.18,0.11,0.0,0.11,0.18,0.27,0.4

'Duplicates'

np.int64(0)

,Data Types,Missing Values,Unique Values,Sample Values
arrival_airport,object,0,104,"[UUD, GRV, IJK]"
total_flights,int64,0,72,"[428, 619, 61]"
total_occupied_seats,int64,0,95,"[524, 283, 0]"
total_available_seats,int64,0,99,"[2928, 19894, 3050]"
load_factor,float64,0,95,"[0.34343949044585986, 0.18523474963755995, 0.0]"

missing values

,arrival_airport,total_flights,total_occupied_seats,total_available_seats,load_factor
0,False,False,False,False,False
1,False,False,False,False,False
2,False,False,False,False,False
3,False,False,False,False,False
4,False,False,False,False,False
...,...,...,...,...,...
99,False,False,False,False,False
100,False,False,False,False,False
101,False,False,False,False,False
102,False,False,False,False,False
103,False,False,False,False,False

name of table: ('bookings',)

'Shape'

(104, 5)

'Description'

,count,mean,std,min,25%,50%,75%,max
total_flights,104.0,318.47,483.64,17.0,120.00,187.00,359.00,3217.0
total_occupied_seats,104.0,5573.90,11807.55,0.0,421.00,2130.50,5997.75,77909.0
total_available_seats,104.0,24481.06,51602.93,528.0,4440.50,9057.50,22280.25,327936.0
load_factor,104.0,0.18,0.11,0.0,0.11,0.18,0.27,0.4

'Duplicates'

np.int64(0)

,Data Types,Missing Values,Unique Values,Sample Values
arrival_airport,object,0,104,"[NYM, TBW, ARH]"
total_flights,int64,0,72,"[79, 140, 183]"
total_occupied_seats,int64,0,95,"[35867, 4101, 8526]"
total_available_seats,int64,0,99,"[20176, 5640, 4464]"
load_factor,float64,0,95,"[0.3745141118810208, 0.16141226134510217, 0.16..."

missing values

,arrival_airport,total_flights,total_occupied_seats,total_available_seats,load_factor
0,False,False,False,False,False
1,False,False,False,False,False
2,False,False,False,False,False
3,False,False,False,False,False
4,False,False,False,False,False
...,...,...,...,...,...
99,False,False,False,False,False
100,False,False,False,False,False
101,False,False,False,False,False
102,False,False,False,False,False
103,False,False,False,False,False

name of table: ('flights',)

'Shape'

(104, 5)

'Description'

,count,mean,std,min,25%,50%,75%,max
total_flights,104.0,318.47,483.64,17.0,120.00,187.00,359.00,3217.0
total_occupied_seats,104.0,5573.90,11807.55,0.0,421.00,2130.50,5997.75,77909.0
total_available_seats,104.0,24481.06,51602.93,528.0,4440.50,9057.50,22280.25,327936.0
load_factor,104.0,0.18,0.11,0.0,0.11,0.18,0.27,0.4

'Duplicates'

np.int64(0)

,Data Types,Missing Values,Unique Values,Sample Values
arrival_airport,object,0,104,"[GDZ, KHV, STW]"
total_flights,int64,0,72,"[18, 411, 61]"
total_occupied_seats,int64,0,95,"[6021, 5990, 2524]"
total_available_seats,int64,0,99,"[6100, 7994, 24887]"
load_factor,float64,0,95,"[0.07537012113055182, 0.2334796088280481, 0.03..."

missing values

,arrival_airport,total_flights,total_occupied_seats,total_available_seats,load_factor
0,False,False,False,False,False
1,False,False,False,False,False
2,False,False,False,False,False
3,False,False,False,False,False
4,False,False,False,False,False
...,...,...,...,...,...
99,False,False,False,False,False
100,False,False,False,False,False
101,False,False,False,False,False
102,False,False,False,False,False
103,False,False,False,False,False

name of table: ('seats',)

'Shape'

(104, 5)

'Description'

,count,mean,std,min,25%,50%,75%,max
total_flights,104.0,318.47,483.64,17.0,120.00,187.00,359.00,3217.0
total_occupied_seats,104.0,5573.90,11807.55,0.0,421.00,2130.50,5997.75,77909.0
total_available_seats,104.0,24481.06,51602.93,528.0,4440.50,9057.50,22280.25,327936.0
load_factor,104.0,0.18,0.11,0.0,0.11,0.18,0.27,0.4

'Duplicates'

np.int64(0)

,Data Types,Missing Values,Unique Values,Sample Values
arrival_airport,object,0,104,"[UFA, SKX, NFG]"
total_flights,int64,0,72,"[175, 2982, 158]"
total_occupied_seats,int64,0,95,"[0, 1155, 6071]"
total_available_seats,int64,0,99,"[25273, 24975, 15214]"
load_factor,float64,0,95,"[0.14935868865448423, 0.1521376085504342, 0.18..."

missing values

,arrival_airport,total_flights,total_occupied_seats,total_available_seats,load_factor
0,False,False,False,False,False
1,False,False,False,False,False
2,False,False,False,False,False
3,False,False,False,False,False
4,False,False,False,False,False
...,...,...,...,...,...
99,False,False,False,False,False
100,False,False,False,False,False
101,False,False,False,False,False
102,False,False,False,False,False
103,False,False,False,False,False

name of table: ('ticket_flights',)

'Shape'

(104, 5)

'Description'

,count,mean,std,min,25%,50%,75%,max
total_flights,104.0,318.47,483.64,17.0,120.00,187.00,359.00,3217.0
total_occupied_seats,104.0,5573.90,11807.55,0.0,421.00,2130.50,5997.75,77909.0
total_available_seats,104.0,24481.06,51602.93,528.0,4440.50,9057.50,22280.25,327936.0
load_factor,104.0,0.18,0.11,0.0,0.11,0.18,0.27,0.4

'Duplicates'

np.int64(0)

,Data Types,Missing Values,Unique Values,Sample Values
arrival_airport,object,0,104,"[KLF, GOJ, UUD]"
total_flights,int64,0,72,"[36, 619, 1902]"
total_occupied_seats,int64,0,95,"[9545, 4432, 2696]"
total_available_seats,int64,0,99,"[68092, 4370, 6100]"
load_factor,float64,0,95,"[0.18523474963755995, 0.2334796088280481, 0.01..."

missing values

,arrival_airport,total_flights,total_occupied_seats,total_available_seats,load_factor
0,False,False,False,False,False
1,False,False,False,False,False
2,False,False,False,False,False
3,False,False,False,False,False
4,False,False,False,False,False
...,...,...,...,...,...
99,False,False,False,False,False
100,False,False,False,False,False
101,False,False,False,False,False
102,False,False,False,False,False
103,False,False,False,False,False

name of table: ('tickets',)

'Shape'

(104, 5)

'Description'

,count,mean,std,min,25%,50%,75%,max
total_flights,104.0,318.47,483.64,17.0,120.00,187.00,359.00,3217.0
total_occupied_seats,104.0,5573.90,11807.55,0.0,421.00,2130.50,5997.75,77909.0
total_available_seats,104.0,24481.06,51602.93,528.0,4440.50,9057.50,22280.25,327936.0
load_factor,104.0,0.18,0.11,0.0,0.11,0.18,0.27,0.4

'Duplicates'

np.int64(0)

,Data Types,Missing Values,Unique Values,Sample Values
arrival_airport,object,0,104,"[BZK, ULV, KUF]"
total_flights,int64,0,72,"[122, 305, 26]"
total_occupied_seats,int64,0,95,"[51, 4101, 616]"
total_available_seats,int64,0,99,"[41480, 5640, 25273]"
load_factor,float64,0,95,"[0.22379032258064516, 0.147780925401322, 0.191..."

missing values

,arrival_airport,total_flights,total_occupied_seats,total_available_seats,load_factor
0,False,False,False,False,False
1,False,False,False,False,False
2,False,False,False,False,False
3,False,False,False,False,False
4,False,False,False,False,False
...,...,...,...,...,...
99,False,False,False,False,False
100,False,False,False,False,False
101,False,False,False,False,False
102,False,False,False,False,False
103,False,False,False,False,False

name of table: ('load_factor_departure_airport',)

'Shape'

(104, 5)

'Description'

,count,mean,std,min,25%,50%,75%,max
total_flights,104.0,318.47,483.64,17.0,120.00,187.00,359.00,3217.0
total_occupied_seats,104.0,5573.90,11807.55,0.0,421.00,2130.50,5997.75,77909.0
total_available_seats,104.0,24481.06,51602.93,528.0,4440.50,9057.50,22280.25,327936.0
load_factor,104.0,0.18,0.11,0.0,0.11,0.18,0.27,0.4

'Duplicates'

np.int64(0)

,Data Types,Missing Values,Unique Values,Sample Values
arrival_airport,object,0,104,"[PEE, TBW, ESL]"
total_flights,int64,0,72,"[244, 17, 192]"
total_occupied_seats,int64,0,95,"[51, 1516, 2696]"
total_available_seats,int64,0,99,"[6100, 92518, 326097]"
load_factor,float64,0,95,"[0.3309899661276922, 0.37264707534977803, 0.19..."

missing values

,arrival_airport,total_flights,total_occupied_seats,total_available_seats,load_factor
0,False,False,False,False,False
1,False,False,False,False,False
2,False,False,False,False,False
3,False,False,False,False,False
4,False,False,False,False,False
...,...,...,...,...,...
99,False,False,False,False,False
100,False,False,False,False,False
101,False,False,False,False,False
102,False,False,False,False,False
103,False,False,False,False,False

name of table: ('load_factor_arrival_airport',)

'Shape'

(104, 5)

'Description'

,count,mean,std,min,25%,50%,75%,max
total_flights,104.0,318.47,483.64,17.0,120.00,187.00,359.00,3217.0
total_occupied_seats,104.0,5573.90,11807.55,0.0,421.00,2130.50,5997.75,77909.0
total_available_seats,104.0,24481.06,51602.93,528.0,4440.50,9057.50,22280.25,327936.0
load_factor,104.0,0.18,0.11,0.0,0.11,0.18,0.27,0.4

'Duplicates'

np.int64(0)

,Data Types,Missing Values,Unique Values,Sample Values
arrival_airport,object,0,104,"[UUS, OVB, NFG]"
total_flights,int64,0,72,"[192, 61, 191]"
total_occupied_seats,int64,0,95,"[3409, 1661, 6374]"
total_available_seats,int64,0,99,"[15214, 8890, 2240]"
load_factor,float64,0,95,"[0.2334796088280481, 0.0, 0.2913977298019141]"

missing values

,arrival_airport,total_flights,total_occupied_seats,total_available_seats,load_factor
0,False,False,False,False,False
1,False,False,False,False,False
2,False,False,False,False,False
3,False,False,False,False,False
4,False,False,False,False,False
...,...,...,...,...,...
99,False,False,False,False,False
100,False,False,False,False,False
101,False,False,False,False,False
102,False,False,False,False,False
103,False,False,False,False,False