In [1]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import sqlite3
from core.data import load_from_kaggle
pd.set_option('display.precision', 2)

c:\Users\yamen\Desktop\Weiterbildung\visual Studio Code\mein-project\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
dataset_link = "saadharoon27/airlines-dataset" # replace with your dataset link from Kaggle 
destination = "../data/raw"
dataset_name = dataset_link.split("/")[-1]

files = load_from_kaggle(
    dataset_link=dataset_link, 
    destination=destination,
    )

Destination directory '../data/raw\airlines-dataset' already exists with files. Skipping download (replace=False).

In [3]:
files

['travel.sqlite']

In [4]:
conn = sqlite3.connect("../data/raw/travel.sqlite")
cursor = conn.cursor()
cursor.execute("SELECT name FROM sqlite_master WHERE type='table'")
tabels = cursor.fetchall()

print(tabels)

[('aircrafts_data',), ('airports_data',), ('boarding_passes',), ('bookings',), ('flights',), ('seats',), ('ticket_flights',), ('tickets',), ('load_factor_departure_airport',), ('load_factor_arrival_airport',)]

In [5]:
df_aircrafts_data=pd.read_sql_query("SELECT * FROM aircrafts_data", conn)
df_boarding_passes=pd.read_sql_query("SELECT * FROM boarding_passes", conn)
df_bookings=pd.read_sql_query("SELECT * FROM bookings", conn)
df_flights=pd.read_sql_query("SELECT * FROM flights", conn)
df_seats=pd.read_sql_query("SELECT * FROM seats", conn)
df_ticket_flights=pd.read_sql_query("SELECT * FROM ticket_flights", conn)
df_tickets=pd.read_sql_query("SELECT * FROM tickets", conn)
print('aircrafts_data')
display(df_aircrafts_data)
print('\n')
print('boarding_passes')
display(df_boarding_passes)
print('\n')
print('bookings')
display(df_bookings)
print('\n')
print('flights')
display(df_flights)
print('\n')
print('seats')
display(df_seats)
print('\n')
print('ticket_flights')
display(df_ticket_flights)
print('\n')
print('tickets')
display(df_tickets)

aircrafts_data

  aircraft_code                                              model  range
0           773    {"en": "Boeing 777-300", "ru": "Боинг 777-300"}  11100
1           763    {"en": "Boeing 767-300", "ru": "Боинг 767-300"}   7900
2           SU9  {"en": "Sukhoi Superjet-100", "ru": "Сухой Суп...   3000
3           320  {"en": "Airbus A320-200", "ru": "Аэробус A320-...   5700
4           321  {"en": "Airbus A321-200", "ru": "Аэробус A321-...   5600
5           319  {"en": "Airbus A319-100", "ru": "Аэробус A319-...   6700
6           733    {"en": "Boeing 737-300", "ru": "Боинг 737-300"}   4200
7           CN1  {"en": "Cessna 208 Caravan", "ru": "Сессна 208...   1200
8           CR2  {"en": "Bombardier CRJ-200", "ru": "Бомбардье ...   2700

boarding_passes

            ticket_no  flight_id  boarding_no seat_no
0       0005435212351      30625            1      2D
1       0005435212386      30625            2      3G
2       0005435212381      30625            3      4H
3       0005432211370      30625            4      5D
4       0005435212357      30625            5     11A
...               ...        ...          ...     ...
579681  0005434302871      19945           85     20F
579682  0005432892791      19945           86     21C
579683  0005434302869      19945           87     20E
579684  0005432802476      19945           88     21F
579685  0005432802482      19945           89     21E

[579686 rows x 4 columns]

bookings

       book_ref               book_date  total_amount
0        00000F  2017-07-05 03:12:00+03        265700
1        000012  2017-07-14 09:02:00+03         37900
2        000068  2017-08-15 14:27:00+03         18100
3        000181  2017-08-10 13:28:00+03        131800
4        0002D8  2017-08-07 21:40:00+03         23600
...         ...                     ...           ...
262783   FFFEF3  2017-07-17 07:23:00+03         56000
262784   FFFF2C  2017-08-08 05:55:00+03         10800
262785   FFFF43  2017-07-20 20:42:00+03         78500
262786   FFFFA8  2017-08-08 04:45:00+03         28800
262787   FFFFF7  2017-07-01 22:12:00+03         73600

[262788 rows x 3 columns]

flights

,flight_id,flight_no,scheduled_departure,scheduled_arrival,departure_airport,arrival_airport,status,aircraft_code,actual_departure,actual_arrival
0,1185,PG0134,2017-09-10 09:50:00+03,2017-09-10 14:55:00+03,DME,BTK,Scheduled,319,\N,\N
1,3979,PG0052,2017-08-25 14:50:00+03,2017-08-25 17:35:00+03,VKO,HMA,Scheduled,CR2,\N,\N
2,4739,PG0561,2017-09-05 12:30:00+03,2017-09-05 14:15:00+03,VKO,AER,Scheduled,763,\N,\N
3,5502,PG0529,2017-09-12 09:50:00+03,2017-09-12 11:20:00+03,SVO,UFA,Scheduled,763,\N,\N
4,6938,PG0461,2017-09-04 12:25:00+03,2017-09-04 13:20:00+03,SVO,ULV,Scheduled,SU9,\N,\N
...,...,...,...,...,...,...,...,...,...,...
33116,33117,PG0063,2017-08-02 19:25:00+03,2017-08-02 20:10:00+03,SKX,SVO,Arrived,CR2,2017-08-02 19:25:00+03,2017-08-02 20:10:00+03
33117,33118,PG0063,2017-07-28 19:25:00+03,2017-07-28 20:10:00+03,SKX,SVO,Arrived,CR2,2017-07-28 19:30:00+03,2017-07-28 20:15:00+03
33118,33119,PG0063,2017-09-08 19:25:00+03,2017-09-08 20:10:00+03,SKX,SVO,Scheduled,CR2,\N,\N
33119,33120,PG0063,2017-08-01 19:25:00+03,2017-08-01 20:10:00+03,SKX,SVO,Arrived,CR2,2017-08-01 19:26:00+03,2017-08-01 20:12:00+03
33120,33121,PG0063,2017-08-26 19:25:00+03,2017-08-26 20:10:00+03,SKX,SVO,Scheduled,CR2,\N,\N

seats

     aircraft_code seat_no fare_conditions
0              319      2A        Business
1              319      2C        Business
2              319      2D        Business
3              319      2F        Business
4              319      3A        Business
...            ...     ...             ...
1334           773     48H         Economy
1335           773     48K         Economy
1336           773     49A         Economy
1337           773     49C         Economy
1338           773     49D         Economy

[1339 rows x 3 columns]

ticket_flights

             ticket_no  flight_id fare_conditions  amount
0        0005432159776      30625        Business   42100
1        0005435212351      30625        Business   42100
2        0005435212386      30625        Business   42100
3        0005435212381      30625        Business   42100
4        0005432211370      30625        Business   42100
...                ...        ...             ...     ...
1045721  0005435097522      32094         Economy    5200
1045722  0005435097521      32094         Economy    5200
1045723  0005435104384      32094         Economy    5200
1045724  0005435104352      32094         Economy    5200
1045725  0005435104389      32094         Economy    5200

[1045726 rows x 4 columns]

tickets

            ticket_no book_ref passenger_id
0       0005432000987   06B046  8149 604011
1       0005432000988   06B046  8499 420203
2       0005432000989   E170C3  1011 752484
3       0005432000990   E170C3  4849 400049
4       0005432000991   F313DD  6615 976589
...               ...      ...          ...
366728  0005435999869   D730BA  0474 690760
366729  0005435999870   D730BA  6535 751108
366730  0005435999871   A1AD46  1596 156448
366731  0005435999872   7B6A53  9374 822707
366732  0005435999873   7B6A53  7380 075822

[366733 rows x 3 columns]

In [6]:
#join flight information with revenue
sql_query = '''SELECT 
    f.flight_id,
    f.departure_airport,
    f.arrival_airport,
    sum(tf.amount) AS revenue
FROM ticket_flights tf
JOIN flights f 
    ON tf.flight_id = f.flight_id
GROUP BY f.flight_id
ORDER BY revenue DESC'''
df_join_flight_info_revenue = pd.read_sql_query(sql_query, conn)
display(df_join_flight_info_revenue)

       flight_id departure_airport arrival_airport   revenue
0           2354               DME             KHV  17146600
1          26212               KHV             DME  17023600
2           2364               DME             KHV  16962100
3           2330               DME             KHV  16900600
4           2329               DME             KHV  16894400
...          ...               ...             ...       ...
22221      17729               NBC             CSY      3100
22222      17690               NBC             CSY      3100
22223      27684               NOZ             OVB      3000
22224      10653               OVB             NOZ      3000
22225      10602               OVB             NOZ      3000

[22226 rows x 4 columns]

In [7]:
#join aircraft code with revenue
sql_query ="""SELECT 
    a.aircraft_code,
    SUM(tf.amount) AS revenue
FROM ticket_flights tf
JOIN flights f 
    ON tf.flight_id = f.flight_id
JOIN aircrafts_data a 
    ON f.aircraft_code = a.aircraft_code
GROUP BY a.aircraft_code
ORDER BY revenue"""
df_join_aircraft_code_revenue=pd.read_sql_query(sql_query, conn)
display(df_join_aircraft_code_revenue)

  aircraft_code     revenue
0           CN1    96373800
1           733  1426552100
2           321  1638164100
3           CR2  1982760500
4           319  2706163100
5           773  3431205500
6           763  4371277100
7           SU9  5114484700

In [8]:
sql_query = """SELECT 
    b.book_ref,
    b.total_amount,
    COUNT(tf.ticket_no) AS tickets
FROM bookings b
JOIN tickets t 
    ON b.book_ref = t.book_ref
JOIN ticket_flights tf 
    ON t.ticket_no = tf.ticket_no
GROUP BY b.book_ref"""

df_total_amount_tickets = pd.read_sql_query(sql_query, conn)
display(df_total_amount_tickets)

       book_ref  total_amount  tickets
0        00000F        265700        2
1        000012         37900        2
2        000068         18100        2
3        000181        131800        8
4        0002D8         23600        2
...         ...           ...      ...
262783   FFFEF3         56000        2
262784   FFFF2C         10800        2
262785   FFFF43         78500        8
262786   FFFFA8         28800        2
262787   FFFFF7         73600        8

[262788 rows x 3 columns]

In [9]:
#calculation of load factor
sql_query = '''with occupied AS (
    SELECT 
        flight_id,
        COUNT(*) AS occupied_seats
    FROM boarding_passes
    GROUP BY flight_id
),

total AS (
    SELECT 
        f.flight_id,
        COUNT(s.seat_no) AS total_seats
    FROM flights f
    JOIN seats s 
        ON f.aircraft_code = s.aircraft_code
    GROUP BY f.flight_id
)

SELECT 
    o.flight_id,
    o.occupied_seats,
    t.total_seats,
    o.occupied_seats * 1.0 / t.total_seats AS load_factor
FROM occupied o
JOIN total t 
    ON o.flight_id = t.flight_id'''

df_load_factor = pd.read_sql_query(sql_query, conn)
display(df_load_factor)

       flight_id  occupied_seats  total_seats  load_factor
0              1              79          170         0.46
1              2             101          170         0.59
2              3              97          170         0.57
3             17             101          170         0.59
4             18              96          170         0.56
...          ...             ...          ...          ...
11513      33115              20           50         0.40
11514      33116              17           50         0.34
11515      33117              16           50         0.32
11516      33118              16           50         0.32
11517      33120              13           50         0.26

[11518 rows x 4 columns]

In [32]:
#flights with load factor more than 85%
df_load_fctor_over_85 = df_load_factor[df_load_factor['load_factor']>0.8]
print('flights with load factor more than 85%')
display(df_load_fctor_over_85)

flights with load factor more than 85%

       flight_id  occupied_seats  total_seats  load_factor
64           249             365          402         0.91
65           250             361          402         0.90
69           259             346          402         0.86
70           265             323          402         0.80
72           268             355          402         0.88
...          ...             ...          ...          ...
11386      32702              45           50         0.90
11387      32761              11           12         0.92
11388      32767              12           12         1.00
11389      32793              11           12         0.92
11390      32796              12           12         1.00

[2304 rows x 4 columns]

In [11]:
#analysing of load factor with departure airport
sql_query = '''WITH occupied AS (
    SELECT 
        f.flight_id,
        f.departure_airport,
        COUNT(bp.seat_no) AS occupied_seats
    FROM flights f
    LEFT JOIN boarding_passes bp 
        ON f.flight_id = bp.flight_id
    GROUP BY f.flight_id, f.departure_airport
),

capacity AS (
    SELECT 
        f.flight_id,
        COUNT(s.seat_no) AS total_seats
    FROM flights f
    JOIN seats s 
        ON f.aircraft_code = s.aircraft_code
    GROUP BY f.flight_id
)

SELECT 
    o.departure_airport,
    COUNT(o.flight_id) AS total_flights,
    SUM(o.occupied_seats) AS total_occupied_seats,
    SUM(c.total_seats) AS total_available_seats,
    
    SUM(o.occupied_seats) * 1.0 / SUM(c.total_seats) AS load_factor

FROM occupied o
JOIN capacity c 
    ON o.flight_id = c.flight_id

GROUP BY o.departure_airport
ORDER BY load_factor DESC'''
df_load_factor_departure_airport = pd.read_sql_query(sql_query, conn)
df_load_factor_departure_airport.to_sql(
    name="load_factor_departure_airport",
    con=conn,
    if_exists="replace",
    index=False
)
display(df_load_factor_departure_airport)

,departure_airport,total_flights,total_occupied_seats,total_available_seats,load_factor
0,URJ,122,4352,11834,0.37
1,KVX,366,9146,25132,0.36
2,MCX,200,6220,17747,0.35
3,NNM,157,2608,7850,0.33
4,AAQ,131,4942,15017,0.33
...,...,...,...,...,...
99,KYZ,43,0,820,0.00
100,JOK,261,0,3778,0.00
101,IWA,34,0,1700,0.00
102,IAR,79,0,1632,0.00
103,EYK,53,0,978,0.00

In [12]:
#analysing of load factor with arrival airport
sql_query = '''WITH occupied AS (
    SELECT 
        f.flight_id,
        f.arrival_airport,
        COUNT(bp.seat_no) AS occupied_seats
    FROM flights f
    LEFT JOIN boarding_passes bp 
        ON f.flight_id = bp.flight_id
    GROUP BY f.flight_id, f.departure_airport
),

capacity AS (
    SELECT 
        f.flight_id,
        COUNT(s.seat_no) AS total_seats
    FROM flights f
    JOIN seats s 
        ON f.aircraft_code = s.aircraft_code
    GROUP BY f.flight_id
)

SELECT 
    o.arrival_airport,
    COUNT(o.flight_id) AS total_flights,
    SUM(o.occupied_seats) AS total_occupied_seats,
    SUM(c.total_seats) AS total_available_seats,
    
    SUM(o.occupied_seats) * 1.0 / SUM(c.total_seats) AS load_factor

FROM occupied o
JOIN capacity c 
    ON o.flight_id = c.flight_id

GROUP BY o.arrival_airport
ORDER BY load_factor DESC'''
df_load_factor_arrival_airport = pd.read_sql_query(sql_query, conn)
df_load_factor_arrival_airport.to_sql(
    name="load_factor_arrival_airport",
    con=conn,
    if_exists="replace",
    index=False
)
display(df_load_factor_arrival_airport)

,arrival_airport,total_flights,total_occupied_seats,total_available_seats,load_factor
0,AAQ,131,5990,15017,0.40
1,KVX,366,9545,25132,0.38
2,URJ,122,4432,11834,0.37
3,MCX,201,6632,17797,0.37
4,KUF,183,7632,22204,0.34
...,...,...,...,...,...
99,KYZ,44,0,870,0.00
100,JOK,262,0,3828,0.00
101,IWA,36,0,1800,0.00
102,IAR,79,0,1632,0.00
103,EYK,53,0,978,0.00

In [13]:
#calculation of revenue per flight
sql_query = '''SELECT 
    flight_id,
    SUM(amount) AS revenue
FROM ticket_flights
GROUP BY flight_id'''

df_revenue_per_flight = pd.read_sql_query(sql_query, conn)
display(df_revenue_per_flight)

       flight_id  revenue
0              1   693700
1              2   867700
2              3   853600
3              5   800800
4              6   868300
...          ...      ...
22221      33117    87400
22222      33118    86900
22223      33119    21600
22224      33120    70200
22225      33121    98700

[22226 rows x 2 columns]

In [14]:
#comparison of Business vs Economy by calculating of average price
sql_query = '''WITH occupied AS (
    SELECT 
        tf.fare_conditions,
        COUNT(*) AS occupied_seats
    FROM boarding_passes bp
    JOIN ticket_flights tf
        ON bp.ticket_no = tf.ticket_no
       AND bp.flight_id = tf.flight_id
    GROUP BY tf.fare_conditions
),

pricing AS (
    SELECT 
        fare_conditions,
        AVG(amount) AS avg_price,
        COUNT(*) AS total_tickets
    FROM ticket_flights
    GROUP BY fare_conditions
)

SELECT 
    p.fare_conditions,
    o.occupied_seats,
    p.total_tickets,
    p.avg_price
FROM pricing p
LEFT JOIN occupied o
    ON p.fare_conditions = o.fare_conditions'''     
df_fare_condition_comparison = pd.read_sql_query(sql_query, conn)
display(df_fare_condition_comparison)

  fare_conditions  occupied_seats  total_tickets  avg_price
0        Business           59479         107642   51143.42
1         Comfort            9897          17291   32740.55
2         Economy          510310         920793   15959.81

In [15]:
sql_query = '''WITH occupied AS (
    SELECT 
        tf.fare_conditions,
        COUNT(*) AS occupied_seats
    FROM boarding_passes bp
    JOIN ticket_flights tf
        ON bp.ticket_no = tf.ticket_no
       AND bp.flight_id = tf.flight_id
    GROUP BY tf.fare_conditions
)

SELECT 
    tf.fare_conditions,
    tf.amount,
    o.occupied_seats
FROM ticket_flights tf
LEFT JOIN occupied o
    ON tf.fare_conditions = o.fare_conditions'''

df_fare_condition = pd.read_sql_query(sql_query, conn)
display(df_fare_condition)
median_table = df_fare_condition.groupby('fare_conditions').agg(
        occupied_seats=('occupied_seats', 'first'),
        total_tickets=('amount', 'count'),
        median_price=('amount', 'median')).round(3).reset_index()
print('comparison of fare conditions by calculationg the median of prices for each group')
display(median_table)

        fare_conditions  amount  occupied_seats
0              Business   42100           59479
1              Business   42100           59479
2              Business   42100           59479
3              Business   42100           59479
4              Business   42100           59479
...                 ...     ...             ...
1045721         Economy    5200          510310
1045722         Economy    5200          510310
1045723         Economy    5200          510310
1045724         Economy    5200          510310
1045725         Economy    5200          510310

[1045726 rows x 3 columns]

comparison of fare conditions by calculationg the median of prices for each group

  fare_conditions  occupied_seats  total_tickets  median_price
0        Business           59479         107642       35000.0
1         Comfort            9897          17291       24400.0
2         Economy          510310         920793       12100.0

In [16]:
#calculation of revenue per seat
sql_query = '''WITH revenue AS (
    SELECT 
        flight_id,
        SUM(amount) AS total_revenue
    FROM ticket_flights
    GROUP BY flight_id
),

seats_total AS (
    SELECT 
        f.flight_id,
        COUNT(s.seat_no) AS total_seats
    FROM flights f
    JOIN seats s 
        ON f.aircraft_code = s.aircraft_code
    GROUP BY f.flight_id
)

SELECT 
    r.flight_id,
    r.total_revenue,
    s.total_seats,
    r.total_revenue * 1.0 / s.total_seats AS revenue_per_seat
FROM revenue r
JOIN seats_total s 
    ON r.flight_id = s.flight_id
ORDER BY revenue_per_seat DESC'''

df_revenue_per_seat = pd.read_sql_query(sql_query, conn)
display(df_revenue_per_seat)

       flight_id  total_revenue  total_seats  revenue_per_seat
0           2354       17146600          222          77236.94
1          26212       17023600          222          76682.88
2           2364       16962100          222          76405.86
3           2330       16900600          222          76128.83
4           2329       16894400          222          76100.90
...          ...            ...          ...               ...
22221      14672           3200           97             32.99
22222      14714           3200           97             32.99
22223      10602           3000           97             30.93
22224      10653           3000           97             30.93
22225      27684           3000           97             30.93

[22226 rows x 4 columns]

In [33]:
#binding revenue per seat with the type of aircraft
sql_query = '''
WITH revenue AS (
    SELECT 
        f.flight_id,
        f.aircraft_code,
        SUM(tf.amount) AS total_revenue
    FROM ticket_flights tf
    JOIN flights f ON tf.flight_id = f.flight_id
    GROUP BY f.flight_id, f.aircraft_code
),

seats_total AS (
    SELECT 
        aircraft_code,
        COUNT(seat_no) AS total_seats
    FROM seats
    GROUP BY aircraft_code
)

SELECT 
    r.aircraft_code,
    AVG(r.total_revenue * 1.0 / s.total_seats) AS avg_revenue_per_seat,
    a.model
FROM revenue r
JOIN seats_total s 
    ON r.aircraft_code = s.aircraft_code
JOIN  aircrafts_data a
    ON r.aircraft_code = a.aircraft_code
GROUP BY r.aircraft_code, a.model
ORDER BY avg_revenue_per_seat DESC'''
df_revenue_per_seat_aircraft = pd.read_sql_query(sql_query, conn)
print('binding revenue per seat with the type of aircraft')
display(df_revenue_per_seat_aircraft)

binding revenue per seat with the type of aircraft

,aircraft_code,avg_revenue_per_seat,model
0,319,21864.10,"{""en"": ""Airbus A319-100"", ""ru"": ""Аэробус A319-..."
1,763,16477.35,"{""en"": ""Boeing 767-300"", ""ru"": ""Боинг 767-300""}"
2,773,14015.33,"{""en"": ""Boeing 777-300"", ""ru"": ""Боинг 777-300""}"
3,733,9427.39,"{""en"": ""Boeing 737-300"", ""ru"": ""Боинг 737-300""}"
4,SU9,7607.36,"{""en"": ""Sukhoi Superjet-100"", ""ru"": ""Сухой Суп..."
5,321,7446.88,"{""en"": ""Airbus A321-200"", ""ru"": ""Аэробус A321-..."
6,CR2,5341.49,"{""en"": ""Bombardier CRJ-200"", ""ru"": ""Бомбардье ..."
7,CN1,3159.38,"{""en"": ""Cessna 208 Caravan"", ""ru"": ""Сессна 208..."

In [36]:
#anaylyzing of departure time of flights in days
sql_query = '''SELECT 
    strftime('%Y-%m-%d', substr(f.scheduled_departure, 1, 19)) AS scheduled_departure,
    COUNT(tf.ticket_no) AS total_tickets,
    SUM(tf.amount) AS total_revenue
FROM ticket_flights tf
JOIN flights f 
    ON tf.flight_id = f.flight_id
GROUP BY scheduled_departure
ORDER BY scheduled_departure'''
df_departure_time = pd.read_sql_query(sql_query, conn)
print('anaylyzing of departure time of flights in days')
display(df_departure_time)

anaylyzing of departure time of flights in days

     scheduled_departure  total_tickets  total_revenue
0             2017-07-16             39         292200
1             2017-07-16              5         338900
2             2017-07-16              4          91200
3             2017-07-16             36        2490000
4             2017-07-16              9         574800
...                  ...            ...            ...
9218          2017-09-14             17         140500
9219          2017-09-14             15         630700
9220          2017-09-14              2         128800
9221          2017-09-14              5          24200
9222          2017-09-14              5         430500

[9223 rows x 3 columns]

In [19]:
#analyzing of time of departure in weekdays
sql_query = '''SELECT 
    strftime('%w', substr(f.scheduled_departure, 1, 19)) AS weekday_number,
    
    CASE strftime('%w', substr(f.scheduled_departure, 1, 19))
        WHEN '0' THEN 'Sonntag'
        WHEN '1' THEN 'Montag'
        WHEN '2' THEN 'Dienstag'
        WHEN '3' THEN 'Mittwoch'
        WHEN '4' THEN 'Donnerstag'
        WHEN '5' THEN 'Freitag'
        WHEN '6' THEN 'Samstag'
    END AS weekday_name,

    COUNT(tf.ticket_no) AS total_tickets,
    SUM(tf.amount) AS total_revenue,
    COUNT(DISTINCT f.flight_id) AS total_flights

FROM flights f
JOIN ticket_flights tf
    ON f.flight_id = tf.flight_id

GROUP BY weekday_number
ORDER BY weekday_number'''
df_departure_week_days = pd.read_sql_query(sql_query, conn)
print('analyzing of time of departure in weekdays')
display(df_departure_week_days)

analyzing of time of departure in weekdays

  weekday_number weekday_name  total_tickets  total_revenue  total_flights
0              0      Sonntag         153136     3046656500           3372
1              1       Montag         150442     2995167500           3190
2              2     Dienstag         153804     3033617000           3338
3              3     Mittwoch         149907     2965519400           3236
4              4   Donnerstag         150094     3006934300           3180
5              5      Freitag         141574     2721115600           2803
6              6      Samstag         146769     2997970600           3107

In [20]:
#anaylyzing of departure time of flights in hours
sql_query = '''SELECT 
    strftime('%H', substr(f.scheduled_departure, 1, 19)) AS hour,
    COUNT(tf.ticket_no) AS total_tickets,
    SUM(tf.amount) AS total_revenue
FROM ticket_flights tf
JOIN flights f 
    ON tf.flight_id = f.flight_id
GROUP BY hour'''
df_departure_time_hour= pd.read_sql_query(sql_query, conn)
print('anaylyzing of departure time of flights in hours')
display(df_departure_time_hour)

anaylyzing of departure time of flights in hours

   hour  total_tickets  total_revenue
0    02           4227       42652600
1    03           1584       82398900
2    04           7347      440528800
3    05           9837      664052700
4    06           9156      198891900
5    07          28673      584841100
6    08          39693      718313200
7    09         106563     2479985800
8    10         101906     1824375200
9    11         139148     2974993400
10   12          84888     1949481400
11   13          84289     1349557400
12   14          95815     1476937600
13   15          91075     1217098600
14   16          42964      553865100
15   17          66505     1190128500
16   18          77556     1059932300
17   19          41244      912768900
18   20          13256     1046177500

In [35]:
#anaylyzing of arrival time of flights in days
sql_query = '''SELECT 
    strftime('%Y-%m-%d', substr(f.scheduled_arrival, 1, 19)) AS scheduled_arrival,
    COUNT(tf.ticket_no) AS total_tickets,
    SUM(tf.amount) AS total_revenue
FROM ticket_flights tf
JOIN flights f 
    ON tf.flight_id = f.flight_id
GROUP BY scheduled_arrival
ORDER BY scheduled_arrival'''
df_arrival_time = pd.read_sql_query(sql_query, conn)
print('anaylyzing of arrival time of flights in days')
display(df_arrival_time)

anaylyzing of arrival time of flights in days

     scheduled_arrival  total_tickets  total_revenue
0           2017-07-16             39         292200
1           2017-07-16              4          91200
2           2017-07-16             41         174900
3           2017-07-16             32         277800
4           2017-07-16             28         154600
...                ...            ...            ...
8550        2017-09-14              1          64400
8551        2017-09-14              5         307500
8552        2017-09-15              9         558900
8553        2017-09-15              2         128800
8554        2017-09-15              5         430500

[8555 rows x 3 columns]

In [34]:
#analyzing of arrival time of flights in weekdays
sql_query = '''SELECT 
    strftime('%w', substr(f.scheduled_arrival, 1, 19)) AS weekday_number,
    
    CASE strftime('%w', substr(f.scheduled_arrival, 1, 19))
        WHEN '0' THEN 'Sonntag'
        WHEN '1' THEN 'Montag'
        WHEN '2' THEN 'Dienstag'
        WHEN '3' THEN 'Mittwoch'
        WHEN '4' THEN 'Donnerstag'
        WHEN '5' THEN 'Freitag'
        WHEN '6' THEN 'Samstag'
    END AS weekday_name,

    COUNT(tf.ticket_no) AS total_tickets,
    SUM(tf.amount) AS total_revenue,
    COUNT(DISTINCT f.flight_id) AS total_flights

FROM flights f
JOIN ticket_flights tf
    ON f.flight_id = tf.flight_id

GROUP BY weekday_number
ORDER BY weekday_number'''
df_arrival_week_days = pd.read_sql_query(sql_query, conn)
print('analyzing of arrival time of flights in weekdays')
display(df_arrival_week_days)

analyzing of arrival time of flights in weekdays

  weekday_number weekday_name  total_tickets  total_revenue  total_flights
0              0      Sonntag         153118     3052253000           3367
1              1       Montag         149973     2955287800           3188
2              2     Dienstag         154793     3112584100           3357
3              3     Mittwoch         150034     2974163300           3235
4              4   Donnerstag         149336     2940392700           3174
5              5      Freitag         142298     2787110600           2814
6              6      Samstag         146174     2945189400           3091

In [23]:
#anaylyzing of arrival time of flights in hours
sql_query = '''SELECT 
    strftime('%H', substr(f.scheduled_arrival, 1, 19)) AS hour,
    COUNT(tf.ticket_no) AS total_tickets,
    SUM(tf.amount) AS total_revenue
FROM ticket_flights tf
JOIN flights f 
    ON tf.flight_id = f.flight_id
GROUP BY hour'''
df_arrival_time_hour= pd.read_sql_query(sql_query, conn)
print('anaylyzing of arrival time of flights in hours')
display(df_arrival_time_hour)

anaylyzing of arrival time of flights in hours

   hour  total_tickets  total_revenue
0    01            303       24955300
1    02           4146      367292200
2    03          13392      765202000
3    04          11817      947506300
4    05            207       18767800
5    06            297       12162400
6    07           8117       58899200
7    08           8250       51903500
8    09          44395      787190200
9    10          47130      950455100
10   11         107902     1435195300
11   12          80684      981143800
12   13          97440     2040754200
13   14         112134     2444185200
14   15         117104     2609516300
15   16          95121     1396871500
16   17          74643     1469374300
17   18          82798     1699455700
18   19          65920     1016637400
19   20          73926     1689513200

In [24]:
#calculation of median booking lead time
sql_query = '''SELECT 
    (
        julianday(substr(f.scheduled_departure, 1, 19)) - 
        julianday(substr(b.book_date, 1, 19))
    ) AS booking_lead_time_days
FROM ticket_flights tf
JOIN tickets t 
    ON tf.ticket_no = t.ticket_no
JOIN bookings b
    ON t.book_ref = b.book_ref
JOIN flights f 
    ON tf.flight_id = f.flight_id'''
df_booking_lead_time = pd.read_sql_query(sql_query, conn)
median_booking_lead_time = df_booking_lead_time['booking_lead_time_days'].median()
print(f'Median booking lead time: {median_booking_lead_time:.2f} days')

Median booking lead time: 19.54 days

In [25]:
#calculation of average lead time day for each fare condition
sql_query = '''SELECT 
    tf.fare_conditions,
AVG(
        julianday(substr(f.scheduled_departure, 1, 19)) - julianday(substr(b.book_date, 1, 19))
    ) AS avg_lead_time_days,
    COUNT(*) AS total_tickets
FROM ticket_flights tf
JOIN tickets t 
    ON tf.ticket_no = t.ticket_no
JOIN bookings b
    ON t.book_ref = b.book_ref
JOIN flights f 
    ON tf.flight_id = f.flight_id
GROUP BY tf.fare_conditions
ORDER BY total_tickets DESC
'''
df_avg_booking_lead_time_fare_conditions = pd.read_sql_query(sql_query, conn)
display(df_avg_booking_lead_time_fare_conditions)

  fare_conditions  avg_lead_time_days  total_tickets
0         Economy               20.31         920793
1        Business               20.25         107642
2         Comfort               19.98          17291

In [ ]:
#percentage of occupied seals for each fare condition
sql_query = '''SELECT 
    tf.fare_conditions,
    COUNT(*) AS occupied_seats,
    COUNT(*) * 100.0 / SUM(COUNT(*)) OVER() AS percentage
FROM boarding_passes bp
JOIN ticket_flights tf
    ON bp.ticket_no = tf.ticket_no
   AND bp.flight_id = tf.flight_id
GROUP BY tf.fare_conditions
ORDER BY percentage DESC'''

df_fare_conditions_occupied_seats = pd.read_sql_query(sql_query, conn)
display(df_fare_conditions_occupied_seats)

  fare_conditions  occupied_seats  percentage
0         Economy          510310       88.03
1        Business           59479       10.26
2         Comfort            9897        1.71

In [27]:
#calculation of median lead time day for each fare condition
sql_query = '''SELECT 
    tf.fare_conditions,
(
        julianday(substr(f.scheduled_departure, 1, 19)) - julianday(substr(b.book_date, 1, 19))
    ) AS lead_time_days
FROM ticket_flights tf
JOIN tickets t 
    ON tf.ticket_no = t.ticket_no
JOIN bookings b
    ON t.book_ref = b.book_ref
JOIN flights f 
    ON tf.flight_id = f.flight_id
'''
df_booking_lead_time_fare_conditions = pd.read_sql_query(sql_query, conn)
df_median_booking_lead_time_fare_conditions = df_booking_lead_time_fare_conditions.groupby('fare_conditions')['lead_time_days'].median().reset_index()
df_median_booking_lead_time_fare_conditions['median lead time day'] = df_median_booking_lead_time_fare_conditions['lead_time_days']
df_median_booking_lead_time_fare_conditions = df_median_booking_lead_time_fare_conditions.drop(columns='lead_time_days')
display(df_median_booking_lead_time_fare_conditions)

  fare_conditions  median lead time day
0        Business                 19.46
1         Comfort                 19.19
2         Economy                 19.56

In [28]:
#average price tickets by booking time distribution
sql_query = '''
SELECT 
    CASE 
        WHEN julianday(substr(f.scheduled_departure,1,19)) - julianday(substr(b.book_date,1,19)) <= 3 
            THEN 'Last Minute (0-3 Tage)'
        WHEN julianday(substr(f.scheduled_departure,1,19)) - julianday(substr(b.book_date,1,19)) <= 14 
            THEN 'Kurzfristig (4-14 Tage)'
        WHEN julianday(substr(f.scheduled_departure,1,19)) - julianday(substr(b.book_date,1,19)) <= 30 
            THEN 'Mittelfristig (15-30 Tage)'
        ELSE 'Langfristig (>30 Tage)'
    END AS booking_window,
    
    COUNT(*) AS total_tickets,
    AVG(tf.amount) AS avg_ticket_price
FROM ticket_flights tf
JOIN tickets t 
    ON tf.ticket_no = t.ticket_no
JOIN bookings b
    ON t.book_ref = b.book_ref
JOIN flights f 
    ON tf.flight_id = f.flight_id
GROUP BY booking_window
ORDER BY avg_ticket_price DESC
'''
df_booking_time_distribution = pd.read_sql_query(sql_query, conn)
display(df_booking_time_distribution)

               booking_window  total_tickets  avg_ticket_price
0      Langfristig (>30 Tage)          43448          20401.57
1  Mittelfristig (15-30 Tage)         873012          19852.32
2     Kurzfristig (4-14 Tage)         129266          19721.01

In [29]:
#average price tickets by booking time distribution according to fare conditions
sql_query = '''SELECT 
    tf.fare_conditions,
    CASE 
        WHEN julianday(substr(f.scheduled_departure,1,19)) - julianday(substr(b.book_date,1,19)) <= 3 
            THEN 'Last Minute (0-3 Tage)'
        WHEN julianday(substr(f.scheduled_departure,1,19)) - julianday(substr(b.book_date,1,19)) <= 14 
            THEN 'Kurzfristig (4-14 Tage)'
        WHEN julianday(substr(f.scheduled_departure,1,19)) - julianday(substr(b.book_date,1,19)) <= 30 
            THEN 'Mittelfristig (15-30 Tage)'
        ELSE 'Langfristig (>30 Tage)'
    END AS booking_window,
    COUNT(*) AS total_tickets,
    AVG(tf.amount) AS avg_ticket_price
FROM ticket_flights tf
JOIN tickets t ON tf.ticket_no = t.ticket_no
JOIN bookings b ON t.book_ref = b.book_ref
JOIN flights f ON tf.flight_id = f.flight_id
GROUP BY tf.fare_conditions, booking_window
ORDER BY booking_window, total_tickets DESC'''

df_booking_time_distribution_fare_condition = pd.read_sql_query(sql_query, conn)
display(df_booking_time_distribution_fare_condition)

  fare_conditions              booking_window  total_tickets  avg_ticket_price
0         Economy     Kurzfristig (4-14 Tage)         113452          15900.51
1        Business     Kurzfristig (4-14 Tage)          13416          49723.26
2         Comfort     Kurzfristig (4-14 Tage)           2398          32620.73
3         Economy      Langfristig (>30 Tage)          38498          16465.39
4        Business      Langfristig (>30 Tage)           4364          53419.66
5         Comfort      Langfristig (>30 Tage)            586          33104.61
6         Economy  Mittelfristig (15-30 Tage)         768843          15943.25
7        Business  Mittelfristig (15-30 Tage)          89862          51244.90
8         Comfort  Mittelfristig (15-30 Tage)          14307          32745.73

In [30]:
#median price tickets by booking time distribution according to fare conditions
sql_query ='''SELECT 
tf.fare_conditions, 
CASE 
WHEN julianday(substr(f.scheduled_departure,1,19)) - julianday(substr(b.book_date,1,19)) <= 3 THEN 'Last Minute (0-3 Tage)' 
WHEN julianday(substr(f.scheduled_departure,1,19)) - julianday(substr(b.book_date,1,19)) <= 14 THEN 'Kurzfristig (4-14 Tage)' 
WHEN julianday(substr(f.scheduled_departure,1,19)) - julianday(substr(b.book_date,1,19)) <= 30 THEN 'Mittelfristig (15-30 Tage)' 
ELSE 'Langfristig (>30 Tage)' END AS booking_window, 
tf.amount 
FROM ticket_flights tf 
JOIN tickets t ON tf.ticket_no = t.ticket_no 
JOIN bookings b ON t.book_ref = b.book_ref 
JOIN flights f ON tf.flight_id = f.flight_id
'''
df_prices_time_distribution_fare_condition = pd.read_sql_query(sql_query, conn)
median_table = df_prices_time_distribution_fare_condition.groupby(['fare_conditions', 'booking_window'])['amount'].median().reset_index(name='median_ticket_price')
display(median_table)

  fare_conditions              booking_window  median_ticket_price
0        Business     Kurzfristig (4-14 Tage)              35000.0
1        Business      Langfristig (>30 Tage)              35000.0
2        Business  Mittelfristig (15-30 Tage)              35000.0
3         Comfort     Kurzfristig (4-14 Tage)              24400.0
4         Comfort      Langfristig (>30 Tage)              24400.0
5         Comfort  Mittelfristig (15-30 Tage)              24400.0
6         Economy     Kurzfristig (4-14 Tage)              12100.0
7         Economy      Langfristig (>30 Tage)              12200.0
8         Economy  Mittelfristig (15-30 Tage)              12100.0

In [31]:
#average price of tickets by different booking days
sql_query = ''' SELECT ROUND(
        julianday(substr(f.scheduled_departure, 1, 19)) - julianday(substr(b.book_date, 1, 19))) AS lead_time_days,
    AVG(tf.amount) AS avg_price,
    COUNT(*) AS tickets
FROM ticket_flights tf
JOIN tickets t 
    ON tf.ticket_no = t.ticket_no
JOIN bookings b
    ON t.book_ref = b.book_ref
JOIN flights f 
    ON tf.flight_id = f.flight_id
GROUP BY lead_time_days
ORDER BY lead_time_days'''

df_booking_lead_time_ticket_price = pd.read_sql_query(sql_query, conn)
df_booking_lead_time_ticket_price.head(10)

   lead_time_days  avg_price  tickets
0             5.0   17770.97       31
1             6.0   20861.29       93
2             7.0   21365.15      330
3             8.0   18986.93     1140
4             9.0   20270.60     3170
5            10.0   19926.15     7541
6            11.0   19582.00    15693
7            12.0   19622.25    27800
8            13.0   19808.12    43873
9            14.0   19813.80    60991